package com.totgb.zazzproxy;

import android.content.*;import android.net.*;import android.net.wifi.WifiManager;import android.os.*;import android.view.*;import android.widget.*;import androidx.appcompat.app.*;import androidx.core.content.ContextCompat;import com.google.android.material.bottomnavigation.BottomNavigationView;import com.google.android.material.button.MaterialButton;import com.google.android.material.card.MaterialCardView;import com.google.android.material.materialswitch.MaterialSwitch;import java.io.*;import java.util.*;

/** Programmatic bottom-navigation UI for ZazzProxy. */
public class MainActivity extends AppCompatActivity {
 private static final int BROWSE=1,HOST=2,SETTINGS=3,DEV=4,EM=41,IM=42,ES=43,IS=44; private FrameLayout content;private TextView status,log;private MaterialButton start;private ZazzUdpNode node;private boolean server,running;private WifiManager.MulticastLock lock;
 @Override public void onCreate(Bundle b){AppCompatDelegate.setDefaultNightMode(p().getBoolean("dark_mode",false)?2:1);super.onCreate(b);wifi();LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);content=new FrameLayout(this);content.setId(View.generateViewId());root.addView(content,new LinearLayout.LayoutParams(-1,0,1));root.addView(nav(),new LinearLayout.LayoutParams(-1,dp(76)));setContentView(root);browse();}
 private BottomNavigationView nav(){BottomNavigationView n=new BottomNavigationView(this);n.getMenu().add(0,BROWSE,0,"Browse").setIcon(android.R.drawable.ic_menu_search);n.getMenu().add(0,HOST,1,"Host").setIcon(android.R.drawable.ic_menu_upload);n.getMenu().add(0,SETTINGS,2,"Settings").setIcon(android.R.drawable.ic_menu_manage);n.getMenu().add(0,DEV,3,"Developer").setIcon(android.R.drawable.ic_menu_info_details);n.setOnItemSelectedListener(i->{if(i.getItemId()==BROWSE)browse();else if(i.getItemId()==HOST)host();else if(i.getItemId()==SETTINGS)settings();else developer();return true;});return n;}
 private void browse(){server=false;stop();LinearLayout x=page();x.addView(head("Find files nearby","Encrypted sharing on your local network."));MaterialCardView c=card();LinearLayout b=body();status=text("Not connected",16);b.addView(status);start=button("Start secure discovery");start.setOnClickListener(v->{if(running)stop();else connect();refresh();});b.addView(start);c.addView(b);x.addView(c);x.addView(head("Activity","Servers and transfers appear here."));log=text("Ready.",14);log.setPadding(0,dp(8),0,0);x.addView(log);put(x);}
 private void host(){server=true;stop();connect();getSupportFragmentManager().beginTransaction().replace(content.getId(),new ServerFragment()).commit();}
 private void settings(){stop();LinearLayout x=page();x.addView(head("Settings","Your identity and trusted sharing group."));MaterialCardView c=card();LinearLayout b=body();EditText cn=field("Client name",p().getString("client_name",Build.MODEL),false),sn=field("Server name",p().getString("server_name",Build.MODEL),false),key=field("Network key", "",true);key.setHint("Leave blank to keep current key");b.addView(cn);b.addView(sn);b.addView(key);MaterialSwitch dark=new MaterialSwitch(this);dark.setText("Dark appearance");dark.setChecked(p().getBoolean("dark_mode",false));b.addView(dark);MaterialButton save=button("Save settings");save.setOnClickListener(v->{if(!key.getText().toString().isEmpty()&&key.length()<8){toast("Network key needs 8 characters.");return;}p().edit().putString("client_name",cn.getText().toString()).putString("server_name",sn.getText().toString()).putBoolean("dark_mode",dark.isChecked()).putString("network_key",key.length()==0?p().getString("network_key",""):key.getText().toString()).apply();AppCompatDelegate.setDefaultNightMode(dark.isChecked()?2:1);});b.addView(save);c.addView(b);x.addView(c);x.addView(action("Export .zaZzProxy","Save hosted catalog",v->create(EM,"catalog.zaZzProxy")));x.addView(action("Import .zaZzProxy","Review a catalog",v->open(IM)));x.addView(action("Export .zaZzSettings","Save names and appearance",v->create(ES,"settings.zaZzSettings")));x.addView(action("Import .zaZzSettings","Restore trusted settings",v->open(IS)));put(x);}
 private void developer(){stop();LinearLayout x=page();x.addView(head("Developer console","A fun project built by totgb."));x.addView(action("Run server in background","Persistent notification keeps hosting active",v->background()));x.addView(action("GitHub","github.com/totgb/ZazzProxy-Android",v->url("https://github.com/totgb/ZazzProxy-Android")));x.addView(action("Libraries","Netty · Jackson · Commons Codec · Bouncy Castle · SLF4J · TestNG · Mockito",v->url("https://github.com/totgb/ZazzProxy-Android")));put(x);}
 private void connect(){String k=p().getString("network_key","");if(k.length()<8){toast("Set a shared network key in Settings.");return;}final boolean mode=server;final String name=p().getString(mode?"server_name":"client_name",Build.MODEL);say("Preparing secure connection…");new Thread(()->{try{ZazzUdpNode made=new ZazzUdpNode(this,name,mode,k,callbacks());made.start();node=made;running=true;say(mode?"Hosting securely.":"Scanning securely.");}catch(Exception e){say(e.getMessage());}}).start();}
 private ZazzUdpNode.Callback callbacks(){return new ZazzUdpNode.Callback(){public void onPeer(ZazzUdpNode.Peer q){say("Found "+q.name);if(!server&&q.server&&node!=null)node.requestManifest(q);}public void onManifest(ZazzUdpNode.Peer q,List<ZazzUdpNode.ShareFile> f){files(q,f);}public void onTransfer(String n,long a,long z,boolean u){say((u?"Uploading ":"Downloading ")+n);}public void onComplete(File f){say("Complete: "+f.getName());}public void onFailure(String m){say(m);}};}
 private void files(ZazzUdpNode.Peer q,List<ZazzUdpNode.ShareFile> f){if(f.isEmpty())return;String[] a=new String[f.size()];for(int i=0;i<f.size();i++)a[i]=f.get(i).name+" · "+f.get(i).bytes+" bytes";runOnUiThread(()->new android.app.AlertDialog.Builder(this).setTitle("Files from "+q.name).setItems(a,(d,w)->node.requestDownload(q,f.get(w))).show());}
 public void hostDocument(Uri u,String n,Runnable done){ZazzUdpNode active=node;if(active==null||!server){toast("Open Host and set a network key first.");return;}new Thread(()->{try{active.hostCopy(getContentResolver().openInputStream(u),n);runOnUiThread(done);}catch(Exception e){say(e.getMessage());}}).start();}
 public void removeHostedFile(String name,Runnable done){ZazzUdpNode active=node;if(active==null)return;new Thread(()->{try{active.removeHostedFile(name);runOnUiThread(done);}catch(Exception e){say(e.getMessage());}}).start();}
 public void stopAllNetworking(){stop();}private void stop(){running=false;if(node!=null){node.close();node=null;}}private void refresh(){if(start!=null){start.setText(running?"Stop discovery":"Start secure discovery");status.setText(running?"Connected":"Not connected");}}private void say(String s){runOnUiThread(()->{if(log!=null)log.append("\n• "+s);if(status!=null)status.setText(s);});}
 private void create(int c,String n){startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/json").putExtra(Intent.EXTRA_TITLE,n),c);}private void open(int c){startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("application/json").addCategory(Intent.CATEGORY_OPENABLE),c);}
 @Override public void onActivityResult(int c,int r,Intent d){super.onActivityResult(c,r,d);if(r!=RESULT_OK||d==null)return;try{if(c==EM){try(OutputStream o=getContentResolver().openOutputStream(d.getData())){ZazzArchive.exportManifest(node==null?Collections.emptyList():node.hostedFiles(),"ZazzProxy",o);}}else if(c==ES){try(OutputStream o=getContentResolver().openOutputStream(d.getData())){ZazzArchive.exportSettings(this,o);}}else if(c==IS){try(InputStream i=getContentResolver().openInputStream(d.getData())){ZazzArchive.importSettings(this,i);}}else if(c==IM){try(InputStream i=getContentResolver().openInputStream(d.getData())){toast("Imported "+ZazzArchive.importManifest(i).size()+" catalog entries.");}}}catch(Exception e){toast("Zazz file failed: "+e.getMessage());}}
 private LinearLayout page(){ScrollView s=new ScrollView(this);s.setFillViewport(true);LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(24),dp(28),dp(24),dp(90));s.addView(x,new ScrollView.LayoutParams(-1,-2));LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.VERTICAL);h.addView(s,new LinearLayout.LayoutParams(-1,0,1));return h;}private void put(View v){content.removeAllViews();content.addView(v,new FrameLayout.LayoutParams(-1,-1));}private LinearLayout head(String a,String b){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);TextView h=text(a,29);h.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);x.addView(h);TextView s=text(b,15);s.setPadding(0,dp(5),0,dp(20));x.addView(s);return x;}private TextView text(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);return t;}private MaterialCardView card(){MaterialCardView c=new MaterialCardView(this);c.setRadius(dp(20));c.setCardElevation(dp(2));return c;}private LinearLayout body(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(20),dp(18),dp(20),dp(18));return x;}private View action(String a,String b,View.OnClickListener l){MaterialCardView c=card();LinearLayout x=body();TextView h=text(a,17);h.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);x.addView(h);x.addView(text(b,14));c.addView(x);c.setOnClickListener(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(10);c.setLayoutParams(p);return c;}private MaterialButton button(String s){MaterialButton b=new MaterialButton(this);b.setText(s);b.setAllCaps(false);b.setCornerRadius(dp(14));return b;}private EditText field(String h,String v,boolean secret){EditText e=new EditText(this);e.setHint(h);e.setText(v);e.setSingleLine();if(secret)e.setInputType(129);return e;}private void background(){stop();Intent i=new Intent(this,ZazzBackgroundService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}
 private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}private SharedPreferences p(){return getSharedPreferences("ZazzPrefs",Context.MODE_PRIVATE);}private void toast(String s){runOnUiThread(()->Toast.makeText(this,s,Toast.LENGTH_LONG).show());}private void url(String s){startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(s)));}private void wifi(){WifiManager w=(WifiManager)getApplicationContext().getSystemService(WIFI_SERVICE);if(w!=null){lock=w.createMulticastLock("ZazzProxy");lock.setReferenceCounted(false);lock.acquire();}}@Override protected void onDestroy(){stop();if(lock!=null&&lock.isHeld())lock.release();super.onDestroy();}
}
